### ISSUE TITLE
Error: http.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kamari-swami** [tsduck/tsduck#1134]
Hi, i have performed following steps:

```
git clone https://github.com/tsduck/tsduck.git
make -j10 install
```
build process ran fine (no errors). when i run the below command from bin directory:
`tsp -I http https://tsduck.io/streams/france-dttv/tnt-uhf30-546MHz-2019-01-22.ts -P analyze --json -o ts.json -O drop`

I get following error:
```
* Error: http.so: cannot open shared object file: No such file or directory
* Error: input plugin http not found
```
1. How can I solve this issue?
2. Can i use local .ts file (in loop) as input for performing/testing scrambling function?

**Comment by lelegard** [comment]
Hi @kamari-swami 

This means that you did not build the `http` input plugin with TSDuck. This plugin is normally, for technical reasons, one of the few which are built inside the TSDuck library. It it apparently not built. As a fallback, `tsp` looks for a shared library (and did not find it since there is none).

Use the command `tsp -l` to list all available plugins. If `http` is not in the list of input plugins, it hasn't been built.

Did you read and follow the [build instructions](https://tsduck.io/doxy/building.html) before running `make`? Specifically, did you run `scripts/install-prerequisites.sh` before building TSDuck? If you run one of the supported Linux distros, this script installs all required packages to build a full-featured TSDuck.

To handle limited systems, the build of TSDuck automatically disables features which are not supported in the current system. Specifically, in the case of HTTP, TSDuck uses the development files of `libcurl`. If they are not present, all HTTP features are disabled.

The idea is the following:
- If you want to build a full TSDuck without caring about the details, run  `scripts/install-prerequisites.sh` before building TSDuck.
- If you explicitly need limited features, either do not install the corresponding library development files or use the various `NOxxx=1` make variables to explicitly disable them.
