### ISSUE TITLE
[BUG] Problem with build_doxygen.ps1

### ISSUE THREAD

**Issue by paulhiggs** [tsduck/tsduck#1147]
#### Bug description:
When running build_doxygen.psi in Windows PowerShell the following error is shown before processing files
````
Traceback (most recent call last):
  File "E:\code\tsduck\src\doc\signalization-gen.py", line 97, in <module>
    list_all_structures(output, dtv_dir + "tables", "Tables", "sigxtables")
  File "E:\code\tsduck\src\doc\signalization-gen.py", line 77, in list_all_structures
    for line in input:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 8148: invalid start byte
````

**Comment by lelegard** [comment]
Hi Paul

The error is raised in the Python script which builds a cross-reference of all tables and descriptors. More precisely, the error is raised while reading a source file, a header file of a table or descriptor. The error is an invalid UTF-8 character in the C++ header file. 

I would suggest reviewing the header file you are developing, looking for a non-ASCII character. Generally speaking, I recommend to use ASCII characters only in source files to avoid conflicts in character representation. If another character is absolutely necessary, use UTF-8. Since you develop on Windows, it is possible that your editor is configured to use one of the exotic character tables which is unknown outside the Windows world. This is why I recommend ASCII only is source files. 

Let us know.
