### ISSUE TITLE
IP input command usage

### ISSUE THREAD

**Issue by mhzbg** [tsduck/tsduck#120]
Hello Apologies for writing this as an issue but I cant figure out from documentation how to achieve IP input from localhost unicast udp . 

tsp: TSDuck - The MPEG Transport Stream Toolkit - version 3.13-834 installed via homebrew on OSX.

I have ffmpeg or VLC produce a stream to localhost udp on port 5001. Works fine in these tools. 

However when trying to access the stream from tsp I get the following error. 
Example:
tsp -v -I ip 5001 –P pes –a –v –O drop
tsp: ip: too many parameter

IP input command is tricky to get working. Any help is appreciated. 
Thanks

**Comment by lelegard** [comment]
> Apologies for writing this as an issue

No problem, we all use the so-called "issue tracker" as a discussion forum about TSDuck.

> IP input command is tricky to get working.

Indeed. There were many requests for enhancements on this plugin in the past months, which resulted in many options to handle many specific use cases.

```
tsp -v -I ip 5001 –P pes –a –v –O drop
tsp: ip: too many parameter
```

Your command looks good, visually. Silly question: Did you really type it with a keyboard or did you copy/paste some part of it from the PDF documentation ? I ask this question because a colleague of mine had exactly the same problem once. Microsoft Word tends to convert dashes ('-') into some kind of hyphens. Visually, it does not make much difference but this is not the real ASCII dash which indicates an option. In that case, the following "–P" is interpreted as a parameter of the `ip` plugin since it is not recognised as an option.

I tried to copy/paste your command:
```
$ cat | xxd
tsp -v -I ip 5001 –P pes –a –v –O drop
00000000: 7473 7020 2d76 202d 4920 6970 2035 3030  tsp -v -I ip 500
00000010: 3120 e280 9350 2070 6573 20e2 8093 6120  1 ...P pes ...a 
00000020: e280 9376 20e2 8093 4f20 6472 6f70 0a    ...v ...O drop.
$ 
```
You can see that only the first two '-' are actual dashes (ASCII 0x2D) while others are UTF-8 characters 0xE28093.
