### ISSUE TITLE
[BUG] tstestecmg causing make fail in centos7

### ISSUE THREAD

**Issue by Hakai-Shin** [tsduck/tsduck#1200]
#### Bug description:

running make command in centos7 fails due to issue while compiling tstestecmg

![image](https://user-images.githubusercontent.com/54961206/230734026-5cdc533d-f2b5-48b0-8d98-490c4d2e4c9b.png)

#### How to reproduce:

Command:
make -j10

#### Expected behavior:

make command should build plugins and development library

#### Errors and logs:

~~~
[be sure to surround verbatim log lines with "~~~" lines]
~~~
![image](https://user-images.githubusercontent.com/54961206/230734026-5cdc533d-f2b5-48b0-8d98-490c4d2e4c9b.png)

#### Environment:
 - OS: CENTOS
 - OS version: CentOS Linux release 7.8.2003 (Core)
 - TSDuck full version: tsduck-3.33-3139
 - Installation type: build from source

#### Additional information:
make command in tsduck-3.32 works fine. tsduck-3.32 does not has tstestecmg tool.
The issue with tstestecmg seems to be use of ‘atomic_uint32_t' which is not available in older gcc, this issue could be resolve by using std::atomic\<std::uint32_t\> as suggested in this stackoverflow answer 
https://stackoverflow.com/questions/41541283/atomic-uint32-t-in-namespace-std-does-not-name-a-type-error

**Comment by lelegard** [comment]
Hi @Hakai-Shin 

TSDuck is updated to remain compatible with new operating system versions. When recent features in TSDuck create an issue with obsolete operating system versions, I do not fix them in the general case.  CentOS 7 is old. RedHat clones (no longer CentOS but Alma Linux or Rocky Linux) are at 9.1 level.

That being said, since the two types are strictly identical (one is a typedef of the other), I made the modification. Please check if it works on CentOS 7.
