### ISSUE TITLE
[FEAT] ECM for fixed CW

### ISSUE THREAD

**Issue by sichunqin** [tsduck/tsduck#1299]
Currently, ECM could not be generated when fixed CW is used. 
For test purpose, I would like to use fixed CW and ECM. Any idea to solve the problem? Thanks!

**Comment by lelegard** [comment]
This is not currently possible because this is not a realistic use case.

It depends on what you want to test and why. If using a fixed CW and ECM is really required, you can generate the ECM offline once using `tsgenecm`. Then, you inject this ECM using the plugin `inject` and update the PMT using the plugin `pmt`.

**Comment by sichunqin** [comment]
It helps. Thanks for the reply!

**Comment by sichunqin** [comment]
As suggested, Using plugs can solve the problem.
