### ISSUE TITLE
[BUG] Pkg-Config emits incorrect cflags

### ISSUE THREAD

**Issue by fennewald** [tsduck/tsduck#1305]
#### Bug description:
When compiled and installed using 
```
make CXXFLAGS_STANDARD=-std=c++20 && sudo make CXXFLAGS_STANDARD=-std=c++20 install
```

pkg-config emits the following flags: `--std=c++11 -I/usr/include/tsduck`. The flag `--std=c++11` should not be emitted.

#### How to reproduce:
1. Clone the repo
2. `make CXXFLAGS_STANDARD=-std=c++20`
3. `sudo make CXXFLAGS_STANDARD=-std=c++20 install`
4. `pkg-config --cflags tsduck`

#### Expected behavior:
`tsduck` could choose to emit the updated std flags, or just not to emit standard flags entirely. I understand the latter may be impossible given #1050.

#### Environment:
 - OS: Linux
 - OS version: Ubuntu 22.04
 - TSDuck full version: 3.36-3297
 - Installation type: Compiled from source, `make install`ed

#### Additional information:
The current pkg-config file confuses the meson build system, and results in projects that include tsduck to be unable to use a c++ standard other than 11.

**Comment by lelegard** [comment]
Hi @fennewald 

This is a difficult choice. Pkgconfig is an old infrastructure and not really well adapted to modern projects.

First, there are two independent aspects: _building_ TSDuck and _using_ TSDuck. Building TSDuck using C++20 as you did does not mean that all applications should be compiled with C++20. So, setting `-std=c++20` in the pkgconfig file is not appropriate. 

Building TSDuck requests a minimum level of C++, currently C++11, maybe some more recent version in the future. It can be built with more recent versions such as C++14 or C++20. For the user, there is no real added value in doing so. This is only a way for me to make sure the TSDuck source code remains compatible with different revisions of the language. This is why the CI workflow compiles TSDuck with C++11 and C++20.

Once TSDuck is installed, it shall be usable by applications using _any_ revision of C++, as long as it is sufficiently recent (C++11 or more). The TSDuck binary library is the same for (or compatible with) all revisions, C++11 or more. The TSDuck headers shall be compilable in the context of an application with _any_ post-C++11 revision.

Selecting a revision of the language is the choice of the application and a library has no right to impose a specific version. A minimal revision is acceptable for obvious technical reasons, but not a specific version.

So, we hit here a limitation of pkgconfig:
- To include TSDuck headers, the application must be compiled with a revision of C++11 or more recent, any revision. So, we cannot simply have no `-std` option in `tsduck.pc` because, if the application does not care about C++ revision and specify no `-std` option either, the default revision is older than C++11 and the compilation will fail.
- On the other hand, if we specify one `-std` option in `tsduck.pc`, it may not be suitable to some applications which, for some reason, need another revision.

An ideal solution would be something like "accept any `-std` option coming from the application build system, as long as it is more recent than C++11 and, otherwise, use C++11 by default if the application specified none". Is there some possibility like this with pkgconfig?

Honestly, I never use pkgconfig and don't like very much because it is a remain of the past. So I am pretty ignorant about detailed features like this.

Anyway, imposing a C++ revision in `tsduck.pc` is probably not acceptable in the general case.

So, the current situation is better than nothing for applications which don't care about the C++ revision. But it isn't for some applications. And, for the same reasons, your solution is not acceptable either.

I am currently running out of solutions...

**Comment by fennewald** [comment]
I understand the issue.

Interestingly, I can find examples in the wild of people who want it both ways:
* [Here's a redhat bug](https://bugzilla.redhat.com/show_bug.cgi?id=1271245) about a package _not_ including `-std=c++11`
* [Here's a github issue in Google's re2](https://github.com/google/re2/issues/352) that mirrors this issue.

> [Specify a minimum version]" Is there some possibility like this with pkgconfig?

To my understanding, no.

It's also worth considering that later c++ standards are not always backwards compatible. While everything currently works with C++11,17 and 20, it's entirely possible that down the line C++26 breaks everything, and in that case, it would be "wrong" to support it.

Personally, I believe it's appropriate to simply note in the README "this project must be compiled with C++ >= 11". I understand, however, that many would miss this, and many more build processes would fail. For those reasons, I agree it is not the correct option for tsduck.

However, my use case is still real. Build systems like meson will read and respect pkg-config files, and this will break build processes that use a later standard. It seems ugly that my only option is to continually maintain a fork with the tiny changes in the PR above.

How do you feel about the changes I just pushed to the PR? I added a `NOPCSTD` make variable. If set, the package-config file will not have any `--std` flag set. I understand that I am adding to an already dazzlingly-complex Makefile. If you feel that the changes are too much complextiy for not enough gain, I think it's fair to just close this issue.

**Comment by lelegard** [comment]
OK for the `make` variable which removes `-std` from the pkgconfig file. By default, we stay with the safe configuration for default users, forcing C++11. Users which want a neutral installation will use your variable and it is their responsibility to provide C++11 or higher.

Concerning the forward compatibility, a "product with a future" shall always adapt to new revisions of the language. This is what happened with C++20: a developer compiled his application with C++20 (without using the pkgconfig file), got errors on TSDuck headers, and reported them. I immediately adapted the entire code base to C++20, using `#ifdef` when necessary.

Concerning the backward compatibility, we just define a minimum language revision, currently C++11. Before it, no way. After it, we manage and will manage when new revisions appear.
