### ISSUE TITLE
Scrambling uses constant null CW?

### ISSUE THREAD

**Issue by phhusson** [tsduck/tsduck#131]
Hi,

I'm currently playing with tsduck dvb-csa2 scrambler and descrambler (thanks a lot for tsduck btw!)
It seems to me that tsduck is scrambling and descrambling with 0000000000000000 CW.
Here is what I tested:

I scramble a file with:
> tsp -I file clear.ts -P scrambler 12026 --dvb-csa2 --cw 0000000000000002 -O file scrambled.ts

I check with mpv that clear can be read, but that scrambled.ts can't be read.
I check that tsp descrambler generated a readable file.

Then, I try to descramble with tsdecrypt:
> tsdecrypt -Y 00000000000000020000000000000002 -I file://scrambled.ts -O file://descrambled.ts

The resulting descrambled.ts is not readable by mpv.

Then I descramble with 0000000000000000:
> tsdecrypt -Y 00000000000000000000000000000000 -I file://scrambled.ts -O file://descrambled.ts

And the resulting descrambled.ts can be succesfully read by mpv!

To the best of my knowledge, tsdecrypt doesn't know tsduck CAS (anyway there is no ECM/EMM to get any information from), so my understanding is that tsduck definitely scrambled with 0 key.

(Please note that tsdecrypt does the equivalent of tsduck "zap" module, so if you test on dvb, you need to add -M serviceid)

I reproduced it with two input ts coming from two different sources, so I'm fairly confident.

This has been reproduced with both current git master and tsduck packaged in Debian, both when using tsecmg and using constant control-word.

Is there something wrong in my setup?
Or do you have any pointer where I can look at to fix this?

Best regards,

**Comment by lelegard** [comment]
Hi @phhusson,

This is because of entropy reduction, where control word 0000000000000002 is mapped to actual encryption key 0000000000000000. Use option `--no-entropy-reduction` to use the raw 64-bit CW as encryption key. See this [presentation on TS](https://tsduck.io/download/docs/mpegts-introduction.pdf), slide 36, for more details. I assume that your tsdecrypt does not use entropy reduction.

Entropy reduction was used everywhere in production systems until recently where some operators moved to full 64-bit entropy for security reasons (nowadays, brute force attacks on 48-bit entropy CSA2 are possible in real time, with only a small timeshift).

**Comment by phhusson** [comment]
Ah, makes perfect sense.

Thanks a lot for bothering to answer my stupid issue :-)
