### ISSUE TITLE
[Q] Bitrate evaluation degrades when adding plugins in the chain

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1339]
I am noticing that when the tsp is run with many plugin "-P", the bitrate reported is not accurate.
As an example when I run a simple command:

`tsp -I ip 239.0.0.1:5555-l172.16.0.100 -P  bitrate_monitor -p 1 -t 1`
the bitrate reported is quite constant to what I expect at mux output  47.9 Mbps

When i run a chain of plugin:

`tsp --control-port 3001 -m -I ip 239.0.0.1:5555 -l 172.16.0.100 -P bitrate_monitor -p 1 -t 1 -P tables --log-json-line --psi-si --pid 18 --pid 20 --invalid-versions -P analyze --unreferenced-pid-list -i 1 --json-line -P analyze --unreferenced-pid-list -i 10 --json-line=SLOWTAB -P analyze --unreferenced-pid-list -i 5 -c --json-line=ANACONT -O drop

the bitrate reported by the bitrate_monitor plugin has deviation of few 100 Kbps. same for the bitrate collected from the analyze.pid array.

I am not sure if this is related to server performances or something else.
if i use a dektec (sw based) on the same server where the bitrate is evaluated in 1s window with ticks of 100ms it is accurate.

@lelegard  any suggestion on this? My goal it to collect TS and pids bitrate every 1s.
thanks for the feedback

`

**Comment by lelegard** [comment]
Each plugin executes in its own thread. So, the more threads you have, the more context switches. Additionally, a plugin with lots of computing may introduce latency, before passing packets to the next plugin.

In your case, bitrate_monitor is kept as first plugin, after the input plugin. With ip input, each UDP datagram is immediately passed to the next plugin. So, there should be no explicit delay. I would have a different opinion if bitrate_monitor was last because it would be called after all accumulated latencies of all previous plugins.

Maybe your system is overloaded, meaning that the thread running bitrate_monitor is not scheduled as fast as expected. The other plugins you use are relatively lightweight. They should not overload the system. Either your system was already heavily loaded, just below the limit, and the additional plugins were enough to throttle the memory or CPU. Or you have additional processes.

Use htop (Linux) or the task manager (Windows) to troubleshoot this. This becomes a system tuning issue.

Concerning the comparison with Dektec software (or any specialized realtime streamer), this is not surprising. TSDuck is a generic lab framework for TS manipulation. It does its best to be responsive enough but it cannot compete with specialized realtime tools. It hasn't been designed for that.
