### ISSUE TITLE
[Q] history plugin

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1383]
v: 3.36-3521 on windows 10

With the following command i get the following output.
```
tsp -I  ip 239.0.0.1:5555 -l 10.0.0.100  -P history  -O drop
* Warning: history: bitrate unknown or too low, use option --suspend-packet-threshold
```
according to manual 

> --suspend-packet-threshold value
> Number of packets in the TS after which a PID is considered as suspended. By default, if no packet is found in a PID during 60 seconds (according to the TS bitrate), the PID is considered as suspended.

Am I missing something?
thanks!

**Comment by lelegard** [comment]
Hi @enricovittorini 

This is an interaction problem between `-I ip` and `-P history`. I will fix this.

In the meantime, use `-P history -s 400000`.

In details, the `history` plugin tries to detect PID's which disappear (and eventually reappear). For this, it determines the maximum time between two packets of the same PID. By default, it uses 60 seconds. In practice, it needs to translate this into a maximum number of packets. Therefore, it needs to know the bitrate.

The bitrate is determined from PCR, never from wall-clock time between packets because `tsp` needs to work equally on online and offline streams.

When `tsp` starts, it initially reads a large number of packets, usually enough to get enough PCR's to compute the initial bitrate. There is one exception, the `ip` input plugin always reads UDP datagram per datagram, which is never enough to get an initial bitrate.

In the `history` plugin, the bug is that the plugin wants to know the initial bitrate, or it fails. This is why it always fails with the `ip` input plugin (which also means that no one ever used `-I ip` and `-P history` together).

The workaround I gave above is to use a specific number of packets instead of using the bitrate. The value 400000 corresponds to the number of packets in 60 s at 10 Mb/s. You may choose another value if you prefer.
