### ISSUE TITLE
[Q] stream_type 0xC0 (192) reported as unknown from analyze plugin

### ISSUE THREAD

**Issue by enricovittorini** [tsduck/tsduck#1385]
I am using tsduck 3.36-3528 on windows 10

analyze plugin, in the pid list,  reports pid with stream_type 192 as Unknown. 
shouldn't it be "private data"?

`{
			"audio": false,
			"bitrate": 17755,
			"bitrate-204": 19266,
			"description": "unknown (0xC0)",
			"ecm": false,
			"emm": false,
			"global": false,
			"id": 666,
			"is-scrambled": false,
			"packets": {
				"af": 0,
				"clear": 97,
				"discontinuities": 0,
				"dts": 0,
				"dts-leap": 0,
				"duplicated": 0,
				"invalid-scrambling": 0,
				"pcr": 0,
				"pcr-leap": 0,
				"pts": 0,
				"pts-leap": 0,
				"scrambled": 0,
				"total": 97
			},
			"pmt": false,
			"service-count": 9,
			"services": [
				14205,
				14206,
				14209,
				14210,
				14212,
				14239,
				14255,
				14256,
				14260
			],
			"t2mi": false,
			"unit-start": 97,
			"unreferenced": false,
			"video": false
		},`
thanks

**Comment by lelegard** [comment]
ISO 13818-1 (MPEG-2 TS) says that stream types 0x80 to 0xFF are "user private". However, within the context of higher level standards, some of these values have known meaning. For 0xC0, it is just unknown...

0xC0 to 0xD0 used to be used by Canal+ a long time ago, when I was working there. Since there were so many technical changes in the meantime, I do not know if their previous private interpretations are still valid (these stream types are still there but commented out in the `tsduck.dtv.names` file).
