### ISSUE TITLE
[Q]  LCN not applied

### ISSUE THREAD

**Issue by TrusterBSW** [tsduck/tsduck#1442]
Hello, I'm currently trying to make my own TV channel.
I'm using a HackRF one and GNU-Radio DTV exemple.

So far i was able to transmit video, and thanks to TSDuck, i was able to rename the services/channels to what I liked.
But I'm not able to change the channel number.

From the documentation and it's exemples, i edited my command to this :
~~~
tsp -v \
    -I file \
    -P tsrename -t 9 -a \
    -P svrename hd1 -l 41 -n "BsW4 TV1" -p "BILLYs Diffusion" -i 0x0901 \
    -P svrename hd2 -l 42 -n "BsW4 TV2" -p "BILLYs Diffusion" -i 0x0902 \
    -P svrename hd3 -l 43 -n "BsW4 TV3" -p "BILLYs Diffusion" -i 0x0903 \
    -P svrename radio1 -l 51 -n "BsW4 Radio1" -p "BILLYs Diffusion" -t 2 -i 0x0910 \
    -P svrename radio2 -l 52 -n "BsW4 Radio2" -p "BILLYs Diffusion" -t 2 -i 0x0911 \
    -P svrename radio3 -l 63 -n "BsW4 Radio3" -p "BILLYs Diffusion" -t 2 -i 0x0912 \
    -O file > test4.mpegts
~~~

i start the transmission, and then a scan to search for my channel :

~~~
tsscan --uhf-band  -c uhf-21 --verbose -g -r france -l
scanning channel 21, 474,000,000 Hz
* UHF channel 21 (474 MHz), locked: no
  Transport stream id: 9, 0x0009

  Name        Provider         ServId TSId   ONetId Type PMTPID
  ----------- ---------------- ------ ------ ------ ---- ------
  BsW4 TV1    BILLYs Diffusion 0x0901 0x0009 0xFF01 0x01 0x1000 
  BsW4 TV2    BILLYs Diffusion 0x0902 0x0009 0xFF01 0x01 0x1001 
  BsW4 TV3    BILLYs Diffusion 0x0903 0x0009 0xFF01 0x01 0x1002 
  BsW4 Radio1 BILLYs Diffusion 0x0910 0x0009 0xFF01 0x02 0x1003 
  BsW4 Radio2 BILLYs Diffusion 0x0911 0x0009 0xFF01 0x02 0x1004 
  BsW4 Radio3 BILLYs Diffusion 0x0912 0x0009 0xFF01 0x02 0x1005 

scanning channel 22, 482,000,000 Hz
~~~

But no LCN.
For exemple if I use the public network here is the result : 
~~~
tsscan --uhf-band  -c uhf-21 --verbose -g -r france -l
scanning channel 21, 474,000,000 Hz
* UHF channel 21 (474 MHz), locked: no
  Transport stream id: 3, 0x0003

  LCN Name               Provider       ServId TSId   ONetId Type PMTPID
  --- ------------------ -------------- ------ ------ ------ ---- ------
    4 CANAL+             CNH            0x0301 0x0003 0x20FA 0x19 0x0384 
   26 LCI                CNH            0x0308 0x0003 0x20FA 0x16 0x01F4 
   45 BFM BUSINESSS      Harmonic       0x1EF1 0x0003 0x20FA 0x01 0x0064 
   46 CANAL INFO TNT SFR SFR            0x1EF2 0x0003 0x20FA 0x01 0x0030 
  451 EUROPE 1                          0x214E 0x0003 0x20FA 0x02 0x083F 
  452 RMC                FM-DVB TDF RMV 0x214F 0x0003 0x20FA 0x02 0x100E 
  453 RTL                               0x2150 0x0003 0x20FA 0x02 0x083E 
  454 FRANCE INFO                       0x2149 0x0003 0x20FA 0x02 0x0838 
  455 FRANCE INTER                      0x214A 0x0003 0x20FA 0x02 0x0839 
  456 FRANCE BLEU                       0x214B 0x0003 0x20FA 0x02 0x083B 
  457 NOSTALGIE                         0x2155 0x0003 0x20FA 0x02 0x087A 
  458 NRJ                               0x2158 0x0003 0x20FA 0x02 0x0870 
  459 SKYROCK                           0x215B 0x0003 0x20FA 0x02 0x0873 
  460 FUN RADIO                         0x215C 0x0003 0x20FA 0x02 0x0874 
~~~
 
I don't understant what I'm missing to apply my LCN

**Comment by lelegard** [comment]
Hi @TrusterBSW 

The plugin `svrename` _renames_ the service in existing tables. It does not _create_ new information, no new tables, no new descriptor. A service is always referenced in PAT and PMT, this is the mandatory required minimum. Other information are referenced in optional tables, such as SDT (name and provider), NIT (LCN), BAT, etc. If the corresponding table does not exist or if the service is not referenced in these tables, no information will be changed.

So, if the services have no previous LCN, there is nothing to rename.

The LCN is a non-standard concept. It is defined neither by MPEG nor DVB. Each country or operator uses its own private descriptor to define LCN. Since you apparently uses the French DTTV network (TNT), the local convention is to define LCN's in an EACEM-defined private descriptor, the eacem_logical_channel_number_descriptor.

See an [example here](https://tsduck.io/streams/france-dttv/tnt-uhf30-546MHz-2019-01-22.psi.txt):
~~~
* NIT Actual, TID 64 (0x40), PID 16 (0x0010)
  Version: 30, sections: 1, total size: 635 bytes
  - Section 0:
    Network Id: 8442 (0x20FA)
    Network information:
    - Descriptor 0: Network Name (0x40, 64), 1 bytes
      Name: "F"
    Transport Stream Id: 1 (0x0001), Original Network Id: 8442 (0x20FA)
....
    - Descriptor 1: Private Data Specifier (0x5F, 95), 4 bytes
      Specifier: 0x00000028 (EACEM/EICTA)
    - Descriptor 2: Logical Channel Number (0x83, 131), 104 bytes
      Service Id:   257 (0x0101), Visible: 1, Channel number:   2
      Service Id:   260 (0x0104), Visible: 1, Channel number:  14
      Service Id:   261 (0x0105), Visible: 1, Channel number:  19
      Service Id:   262 (0x0106), Visible: 1, Channel number:  27
      Service Id:   275 (0x0113), Visible: 1, Channel number:   3
      Service Id:   277 (0x0115), Visible: 1, Channel number:   3
      Service Id:   281 (0x0119), Visible: 1, Channel number:   3
....
    Transport Stream Id: 2 (0x0002), Original Network Id: 8442 (0x20FA)
....
    - Descriptor 1: Private Data Specifier (0x5F, 95), 4 bytes
      Specifier: 0x00000028 (EACEM/EICTA)
    - Descriptor 2: Logical Channel Number (0x83, 131), 20 bytes
      Service Id:   513 (0x0201), Visible: 1, Channel number:   8
      Service Id:   515 (0x0203), Visible: 1, Channel number:  15
      Service Id:   516 (0x0204), Visible: 1, Channel number:  16
      Service Id:   517 (0x0205), Visible: 1, Channel number:  17
      Service Id:   518 (0x0206), Visible: 1, Channel number:  18
....
~~~

If there is no such descriptor in the NIT Actual for your transport stream, or if your services are not referenced in it, there is nothing to rename.

In that case, you need to update the NIT Actual, add the description of your TS, add the private data specifier descriptor and EACEM LCN descriptor with all your services. Directly assign the final LCN in it so that there is no need to rename later.

If you just want to test your TS on a local broadcast cable and rescan your TV set, simply create a minimal NIT in your TS. If you inject in a common cable, in addition to the antenna signal, the TV set will receive all TS, the ones from the antenna and yours. Then, the behaviour will probably depend on the TV set model and brand. Normally, the NIT should be identical on all TS of the network and a TV set may use one and ignore others, or the last one - if different - may override the previous one. Alternatively, some TV sets may accumulate distinct information from the various NIT Actual in the various TS.

In the second case, this is simple. Just create a NIT Actual in your TS, describing your TS only, with the appropriate LCN descriptors. Just try for a start.

If your TV set relies on the consistency of the NIT Actual in all TS, then it may ignore divergent NIT's. In that case, your TS must carry the same NIT as the other TS. However, more complicated, you must update and add the description of your TS in the NIT Actual of all TS, including those from the antenna. Since this requires a lot more equipment, I suggest to start with the first case.
