### ISSUE TITLE
[BUG] file input reopen issue

### ISSUE THREAD

**Issue by izhar-novelsat** [tsduck/tsduck#1474]
#### Bug description:

when reading for a pipe using the -I file command with -i option, everything works, but if the application writing to the pipe (FFMPEG) is closed and reopened, the output stream has errors
#### How to reproduce:

tsp --d -I file /tmp/stream -i -P regulate -O ip 231.1.1.1:30001 -l 10.10.10.125

start FFMPEG with output to /tmp/stream
everything  works!
from tsp output :  * Debug: file: initial buffer load: 44,620 packets, 8,388,560 bytes
stop, wait few seconds and restart FFMPEG.  
from tsp output : * Debug: file: closing and reopening /tmp/stream
initial buffer load message is not printed again - I suspect this is the cause of the issue.
output stream now show PCR repetition errors (I must admit I found it is strange that only this particular error shows)
if FFMPEG is stopped for only a short period (probably input buffer is not completely emptied), everything continues to work just fine.

#### Errors and logs:

~~~
[be sure to surround verbatim log lines with "~~~" lines]
~~~

#### Environment:
 - OS: Linux
 - OS version: Ubuntu 20.04
 - TSDuck full version: 3.27-2397
 - Installation type:  official binary

**Comment by lelegard** [comment]
Hi @izhar-novelsat 

I assume that `/tmp/stream` is a named pipe.

> initial buffer load message is not printed again - I suspect this is the cause of the issue.

No, this is just a message that `tsp` writes once at startup and never again. When `tsp` starts, it starts the input plugin only and initially loads the global buffer with enough packets to hopefully compute the initial bitrate, before starting the other plugins in the chain. The idea is that the other plugins could have a realistic idea of the bitrate at startup. Then, the input bitrate is permanently re-evaluated, based on PCR values. If the input plugin does some internal restart (such as reopening a file), this is transparent to `tsp`.

> output stream now show PCR repetition errors (I must admit I found it is strange that only this particular error shows)

What are the exact error messages and which application reports them? Is it `tsp` (I don't see where) or a receiver downstream, reading the IP stream?

The PCR are generated by `ffmpeg`, based on its output bitrate. If you kill `ffmpeg` and restart it, it is probable that it restarts the PCR counting at zero. So, PCR values are obviously repeated across `ffmpeg` restarts. Since `tsp` absorbs the failures/restarts, it sends a continuous flow of packets to the receivers. In that continuous flow, the PCR values are quite probably restarted and replayed at the points where ffmpeg restarts.

There is another nasty consequence to the PCR discontinuities, inside `tsp`, because you use `-P regulate` without further option. The plugin regulates the output based on some bitrate. By default, it is based on the input bitrate which is constantly re-evaluated by `tsp`, based on PCR values. When the PCR breaks, the bitrate computation is affected and so is the regulation. Probably not much, but still.

If your stream is CBR and you know the bitrate, use `-P regulate --bitrate XXX`. Otherwise, use `-P regulate --pcr-synchronous`. It uses the precise PCR intervals to regulate. In case of PCR discontinuities, it should detect the glitch and restart the regulation.

And, BTW, version 3.27 is obsolete (3 years old). The current version is 3.37, 10 versions ahead. However, it probably does not matter in that case.

Finally, please take care of the type of issue you report. A "bug" is a proven deficiency in TSDuck, a proven misbehavior with a deterministic reproducer. Here, we only have a questionable behavior without proven analysis of the root causes. Reporting false bugs may create confusion.

**Comment by lelegard** [comment]
@izhar-novelsat 
> > And, BTW, version 3.27 is obsolete (3 years old). The current version is 3.37, 10 versions ahead. However, it probably does not matter in that case.
>
> it works so well, I saw no reason to upgarde :)

Not so well since you thought there was a bug :)

In practice, the plugin `regulate` was improved some versions ago, don't remember which one but most certainly after 3.27. The regularity was improved, the output adjustment is now computed on a bit scale instead of TS packet. If the analyzer complains about the interval between PCR, the latest version may improve the situation.
