### ISSUE TITLE
[Q]   TSSCAN  for USA UHF band using Hauppauge WINTV 885 ATSC Tunner

### ISSUE THREAD

**Issue by rhscjohn-dev** [tsduck/tsduck#1537]
When I run the following tsscan, the scan starts at channel 21 and runs thru channel 69
```
tsscan -u --usa --service-list -- verbose -l
```
After the FCC Channel Repack(finished in 2020), the UHF bands start at channel 14 and ends at channel 36.

I tried setting --first-channel  to 14 but that did not work(invalid frequency).

So, how do I perform a channel scan in the US for the UHF channels starting at channel 14.

Total noob on using TSDuck.  Thanks.

**Comment by lelegard** [comment]
Hi @rhscjohn-dev,

Thanks for reporting this. The regional configurations of HF bands are stored in a XML file (see [this section of the user's guide](https://tsduck.io/download/docs/tsduck.html#hfband-config) and [source file here](https://github.com/tsduck/tsduck/blob/master/src/libtsduck/config/tsduck.hfbands.xml)).

The accuracy of this file, especially when local rules change, relies on users' feedback from those regions. Being based in Europe, a DVB land, feedback and experience from users in ATSC and ISDB lands is essential to us. Currently, the "usa" region is configured as:

~~~
  <!-- North America and other ATSC countries -->
  <hfband type="UHF">
    <region name="north-america"/>
    <region name="usa"/>
    <region name="us"/>
    <channels first_channel="14" last_channel="69" base_frequency="473,000,000" channel_width="6,000,000"/>
  </hfband>
~~~

So, thank you for reporting that the new US configuration is UHF channels 14-36 instead of 14-69. I will update this. If you find other obsolete data [in the XML file](https://github.com/tsduck/tsduck/blob/master/src/libtsduck/config/tsduck.hfbands.xml), please let us know.

Now, you have another issue. You mention that the scan starts at 21 up to 69, and reports channel 14 as invalid. This a typical "europe" configuration, which is also the defaut HF region. However, with `tsscan`, the option `--usa` is a shortcut for `--atsc --hf-band-region usa`. So, the region "usa" should have been selected.

Could you please confirm that you have this problem while option `--usa` is used? If this is the case, this is an issue I will investigate.

**Comment by lelegard** [comment]
OK, I reproduced this on a tuner emulator configuration with ATSC captured streams. There is an issue with option `--usa`. It should translate to `--atsc --hf-band-region usa` but it does not. All other "regional package" options such as `--europe`, `--japan`, `--brazil`, etc. translate to their correct set of options, except `--usa`.

I have fixed this. In the meantime, you should replace `--usa` with the explicit options `--atsc --hf-band-region usa`.

If you want to get a fix, you can pull the repo and [rebuild](https://tsduck.io/download/docs/tsduck-dev.html#chap-build) or grab a [nightly build](https://tsduck.io/download/prerelease/) by tomorrow (version 3.39-3903 or higher).

I also fixed the new UHF channel range for USA to 14-36, according to your information.
