### ISSUE TITLE
tsfixcc: Clarification regarding circular option and continuity counters

### ISSUE THREAD

**Issue by cbernander** [tsduck/tsduck#202]
Hi!

I've been working on looping a TS file using the new _pcradjust_ plugin which seems to be working fine. However, I do get discontinuity errors (in VLC) on all the PIDs when the file wraps. I have tried to fix this by running the **tsfixcc** utility with the _circular_ option, but to no avail. When examining the packets in the resulting stream, it seems that there are no continuity counter gaps for any of the PIDs when the file wraps.

However, from what I can tell, according to ISO 13818-1, the continuity counter should _not_ be incremented when the TS packet does _not_ contain a payload (i.e. only contains the adaptation field). So appending packets for any PID without payload at the end of a TS file will probably do nothing to ensure circular continuity.

Have I understood this correctly? And if so, is there any feasible way to implement the _circular_ option properly?

**Comment by lelegard** [comment]
Yes, you are right, the way `tsfixcc --circular` is implemented is not fully compliant with the standard. It adds empty packets (no payload) but increments the continuity counter. I see no way to implement this feature in `tsfixcc` (one single file) in a strictly standard way. If a player checks that CC are contiguous _and also_ that packets without payload do not increment the CC, then it will report a discontinuity in both cases.

There could be two dirty ways to stop players complying with discontinuities:

- Adds final packets with a non-empty payload (one 0x00 or 0xFF byte for instance). This payload would be demuxed into the ES (audio, video, section, etc), resulting into an invalid payload. But since a TS file is probably an abruptly truncated live stream, the content at the loopback point is probably incorrect anyway.

- Do not _add_ any packet but _truncate_ each PID (1 to 15 packets) so that continuity is guaranteed. This will break the very last part of the file but the same remark applies about the loopback point being probably incorrect anyway.

That being said, in your particular case, if you repeat a TS file as input to `tsp`, you may also leave the file itself unmodified and fix all CC on the fly:

~~~
tsp -I file foo.ts --infinite -P continuity --fix -P ...
~~~

**Comment by cbernander** [comment]
Thanks for the quick feedback!

I will test using the _continuity_ plugin to fix the counters on the fly, sounds like a viable solution.

May I suggest you update the _tsfixcc_ documentation to clarify that the _circular_ option isn't fully standard compliant?

By the way, when I was trying to figure out a way around the issue, I was contemplating setting the discontinuity indicator on the first packet for each PID in the TS file - the existence of the indicator would likely also trigger some warning messages in most decoders but I figured it could create a more "stable" transport stream - at least in theory. I don't know if that could be a possible option for the _tsfixcc_ plugin given the limitations of the _circular_ option (it doesn't seem as important now if the _continuity_ plugin will do the trick).

Finally, thanks a lot for all the time and work you are dedicating to this project!

**Comment by lars18th** [comment]
Hi,

I readed this thread, and I think it's interesting to comment something about "looping files":

- To achieve a correct infinite play of a file in a loop, two requirements must be met: The start of the file must be a start GOP, and the end of the file must be an end GOP. And this is necessary not only for the video, but also for the audio and other synchronized streams.
- When looping over an _abrupted_ start/end file, then some trick is required, since you can't get a clean loop.

That being said, I suggest to improve the `tsfixcc` tool with:

- A new optional parameter `--clean-loop` that removes initial packets from the file until the first start GOP is found; and it closes the file with the last packet of a complete GOP. With this improvement will be possible to "fix" abrupted files _and_ check correct files.
- And regarding the `--circular` parameter when an empty packet is generated I suggest to add it as it's done at time (that's incrementing the CC counter) but enabling the "Transport Error Indicator" (TEI). This has sense as the only reason to include it it's because one real discontinuity exists in the stream. So, a packet without payload and Adaptation Field with a TEI on is preferable.

What you think?

**Comment by lelegard** [comment]
Removing partial GOP's from start and end of file is a good idea. That would mean a 2-pass processing on the file:

- First pass: locate first and last PUSI in each PID of the stream; analyze the signalization and locate all PES PID's (audio, video, etc)
- Second pass: In all PES PID's, replace all packets before the first PUSI and after the last one by null packets

As this is a 2-pass processing, it will work on disk files only, not as a pipe or stdin.

To enforce continuity, we may use the TEI to forge fake packets _with a payload_, pretending there is an error in them. Without payload, incrementing the CC is incorrect, as mentioned in the first post of this thread. But in that case, the player will likely report a transport error instead of a continuity error. So, if your sole purpose is to remove error reporting, then you miss your target.

In the context of the 2-pass processing which is described above, the only solution I see to be fully compliant with the standard is to analyze the stream content as follow:

- For all PES PID's, create TS packets with an empty PES packet (so with a TS payload) using the same stream type as previous PES packets. In short, reuse the last PES header with a zero payload size.
- For all section PID's, create TS packets with a one-byte 0xFF payload.
- For other unidentified PID type, we don't really know what to do (and we probably don't care).

But this is some effort without real incentive to do it.

**Comment by lars18th** [comment]
Hi @lelegard ,

> it will work on disk files only, not as a pipe or stdin.

Yes! That's `tsfixcc` is doing at time. In fact, a 2-pass processing isn't a real problem if the target are "looping _files_".

> Second pass: In all PES PID's, replace all packets before the first PUSI and after the last one by null packets

I feel it's preferable to "remove" instead of "replace with nulls". As when you play the file, the start and end points are after the initial stuffing and before the last stuffing. So, if you do in this way the null stuff will generate a time gap... Or not?

> But this is some effort without real incentive to do it.

Well, from my point of view there is still not a good open source "TS loop player". And the current implementation of the `tsfixcc` can't handle abrupted files. Any idea (about a tool) to pre-process such files _before_ playing them with TSDuck?

Regards.

**Comment by cbernander** [comment]
For me, the combination of pre-processing the video file using _ffmpeg_ (re-encoding and ts-muxing) and then using tsp with the _file --infinite_, _pcrbitrate_, _regulate_, _pcradjust_ and _continuity_ plugins is good enough. Of course, in my case the source video material is a proper video file as opposed to, say, a partial TS stream capture.

Sure, fixing up a TS file that is broken at the beginning and/or end (without the re-encoding step) sounds like a nice thing to have in TSDuck, but that sounds to me like a feature outside of the scope of the _tsfixcc_ utility since it isn't really about just fixing continuity counters.

**Comment by lars18th** [comment]
Hi @cbernander ,

I aggree with the concept of "fixing" the file with external tools. I feel it's the best solution.
But, almost some "warning" when the loop can't be done "clean" inside the TSDuck can be valuable. This can be used as a verification.

Regards.
