### ISSUE TITLE
Need to access private methods of TSAnalyser

### ISSUE THREAD

**Issue by Latheror** [tsduck/tsduck#245]
Hello,
I started coding a class in our project, as an interface with the TSDuck library. After instantiating a TSAnalyzerReport configuring it, and feeding it packets, I would need to get individual pids information such as those contained in their PIDContext. However, the getPID method is private.

How could I access these information ?

Thank you

**Comment by lelegard** [comment]
Hi,

Usually, methods are private or protected for a reason. The class `TSAnalyzer` contains many  structures and fields which are not safe to be made public. The class `TSAnalyzer` is typically the base for more specialized subclasses such as `TSAnalyzerReport`. These subclass have access to more structures, typically for read-only (otherwise, the analysis can be broken).

It is true that a couple of methods such as `getPID` are private while they manipulate protected structures. To be more consistent, I just moved them as protected. 

This class was one of the first reason to develop TSDuck, more than 10 years ago. So, some discrepancies remain...
