### ISSUE TITLE
ATSC/Windows. Glitch at start of audio streams on one frequency only.

### ISSUE THREAD

**Issue by oviano** [tsduck/tsduck#246]
I don't know if this is a tsduck issue, or a Windows driver issue, but there is one frequency that exhibits a strange problem. It happens every time, so it's not reception/lap of the Gods/day of the week-related.

So with the service I am decoding, the first audio packets on both audio streams fail with an invalid data error when I try and pass them to FFmpeg libraries. So presumably these packets are messed up in some way, although they appearsto have a valid pts/dts, duration, size etc.

I can survive that, by ignoring these packets. The second packet on each audio stream then seems ok, producing no errors inside the FFmpeg libraries when asked to decode it.

Then the third packet arrives, but with the same dts/pts as the second packet. If I ignore the third packet, everything decodes peacefully from then on.

So I can work around it, either by specific code to track the above situation, or something more generic like FFmpeg itself does in such cases, which seems to be to keep the third packet but shift all the timestamps on thereafter.

But it strikes me as rather odd that this happens for both audio streams, and only on this particular frequency. It can't be the transmission (I assume?) because the errors are only at the start of the stream, and for a live transmission there isn't a concept of the "start of the stream", it's just continuous data which we tune into and start receiving at some random point in the middle of it.

I'm less wondering about a fix as to ask whether this type of thing is common and is ignoring packets a reasonable workaround?

An example of a capture exhibiting this problem is the "557.ts" capture I uploaded for the repo recently, specifically the "KSTU-HD" channel, although maybe it happens on the other services in that file I'm not sure.

**Comment by lenosj** [comment]
Do any of the packets in the first and third audio packets have the
continuity or error bits set?
Is it possible that these packets were adjacent to one another before
re-interleave and it's just an artifact of jumping into the middle of a
stream.
Being the third audio packet, this is a long-shot but I don't know the
offset into the stream for the third packets.

**Comment by oviano** [comment]
I just checked, and neither the transport error indicator or discontinuity indicator bits are set for any of the packets received.

**Comment by lelegard** [comment]
Weird or missing packets at the beginning of a capture on Windows is something I have experienced from day 1 (meaning about 10 years ago). I would bet it is a DirectShow issue rather that a driver one since it occurs for me with various brands of tuners, on DVB-S and DVB-T (and ATSC for you). 

May I suggest (again) to use Linux 😉 I have never experienced that on Linux.

In verbose mode, do you see messages such as "tuner packet synchronization lost, dropped NN bytes in NN chunks" ? In that case, the TSDuck `SinkFilter` identified explicitly incorrect data stream coming from DirectShow and tries to recover. But the packet recovery from an incorrect data stream may not always be correct.

As a rule of thumb, on Windows, I recommend to drop a few initial packets. On Windows, I usually use commands like `tsp -I dvb ... -P skip 100 ...`. If this is an application you write with the TSDuck library, simple do not use the first N packets (100 is just an example but a reasonable one).

**Comment by oviano** [comment]
No I don’t see those sync errors. I’ve seen those before (as per my other thread where I was trying to investigate it) but not in this case.

Yes this is my streaming server application linking to the Tsduck libs.

Thanks for the tip re just skipping a bunch of packets early on.
