### ISSUE TITLE
Suggestion: pcradjust plugin "--reallocate" option

### ISSUE THREAD

**Issue by lars18th** [tsduck/tsduck#371]
Hi @lelegard  ,

Regarding the problem commented in #370 , I have another question to obtain a compliant TS: the PCR interval. The issue is not the same, so I comment on it separately.

When using the `pcradjust` plugin the PCR marks are correct. However, the interval in which they appear may be outside the specifications. This problem appears more frequently when doing a mux processing. Then I suggest to add a new option inside the `pcradjust` plugin:

- `-P pcradjust --reallocate [interval,offset]`: This option intends to set the PCR marks at the specified [interval] with a maximum [±offset]. Both are optional, with default values (i.e. interval=50ms and offset=5ms).

The purpose of the `interval` value is self-explanatory. However, the `offset` value is more complicated. When reallocating the PCR marks, you can found three casuistics:

1. A packet with a PCR mark is inside the interval±offset. In this case nothing needs to be changed (except the recalculation of the PCR).
2. A packet with a PCR mark is outside the interval±offset. In this case the PCR mark needs to be removed (now some code inside the library already exists to clear the PCR without changing the payload).
3. Inside the interval±offset no PCR marks exist. In this case an new TS packet is required for the same pid, without payload, and with the PCR only. Here the offset is useful, as you can start to search for a null packet inside the interval pointed by the offset for a suitable null packet.

What you think about this idea? Does it make sense? Do you think it's possible to incorporate it?

As usual I only have words of appreciation for your excellent contribution to this project.
Regards.

**Comment by lars18th** [comment]
Hi @lelegard ,

Any idea to achieve this objective?

Thank you!

**Comment by lelegard** [comment]
This is a superset of #352, isn't it?

**Comment by lelegard** [comment]
Removing a PCR can occur only when the interval with the previous one (possibly one we added) is less than the minimum.

Removing a PCR looks dangerous to me because there is still a risk that there is no way to add a new PCR later (no stuffing). In that case, we create a hole, a larger interval between two PCR's, which is worse than keeping a PCR which appears too soon.

Similarly, there is a risk to remove a PCR in a packet which is the start of a PES packet with PTS/DTS. It is a pity to loose precise synchronization between PCR and PTS/DTS.

I would only add new PCR's when the interval is too large and there is available stuffing.

So, in fact, we are back to #352.

**Comment by lelegard** [comment]
I have implemented #352 (adding missing PCR below a certain interval). I do not plan to remove PCR which are too close. The risks are greater than the advantages (if there is any).

**Comment by lelegard** [comment]
Version 3.18 has been released.

**Comment by lars18th** [comment]
> I have implemented #352 (adding missing PCR below a certain interval). I do not plan to remove PCR which are too close. The risks are greater than the advantages (if there is any).

Thank you! Works flawlessly. :wink:
