### ISSUE TITLE
hides modulator bandwidth issue

### ISSUE THREAD

**Issue by youns88** [tsduck/tsduck#391]
installed latest tsduck and hides ut-100c driver from tsduck downloads
6mhz bandwidth is not working even signal is showing on my spectrum analyzer
8mhz& 7mhz are working great ,then i tried hides it950x_driver but same problem
Ubuntu 18.04.2 LTS

**Comment by lelegard** [comment]
Hi @youns88,

There was a stupid typo in the hides plugin: when 6 MHz was requested as bandwidth, 5 MHz was used instead. Really stupid typo, "5" instead of "6". It looks like noone ever used 6 MHz bandwidth with HiDes modulators.

It is fixed now. But you have to rebuild TSDuck. See [here](https://tsduck.io/doxy/building.html)

Sorry for the inconvenience.
