### ISSUE TITLE
tsResidentBufferTemplate 

### ISSUE THREAD

**Issue by op4ca** [tsduck/tsduck#429]
tsp: /home/thierry/tsduck/src/libtsduck/tsResidentBufferTemplate.h:78: ts::ResidentBuffer<T>::ResidentBuffer(size_t) [with T = ts::TSPacket; size_t = unsigned int]: Assertion `_locked_base < _allocated_base + page_size' failed.
Aborted

How to fix the problem? Please guide me through. Please

**Comment by lelegard** [comment]
Hi @op4ca,

Which TSDuck version are you using and on which platform are you testing?

As a matter of coincidence (or not?), a well-known TSDuck user privately reported the same problem to me a few days ago on a PlutoSDR device. He investigated the problem in depth. I fixed it and pushed the fix.

The problem was due to the specific memory layout of the PlutoSDR, a very small and constrained device, where the allocated memory happened by return virtual memory addresses with MSB set. The problem was a "signed-ness" issue on the memory rounding.

Unless you already use it, please pull the latest repo, rebuild and test.
