### ISSUE TITLE
tsanalyze MPTS over UDP flow

### ISSUE THREAD

**Issue by rodrigodalri** [tsduck/tsduck#493]
how I analyze a multicast flow with tsanalyze? 

I already try:

tsanalyze udp://224.2.2.2:2032?localaddr=192.168.167.250
tsanalyze udp://224.2.2.2:2032

and receive this error message: 

tsanalyze: cannot open file udp://224.2.2.2:2032

**Comment by lelegard** [comment]
The syntax you are using is proprietary to some applications such as VLC where everything is grouped into an URL-like notation. TSDuck uses a plugin approach.

What you want to do is this:
~~~
tsp -I ip 224.2.2.2:2032 --local-address 192.168.167.250 \
    -P until --seconds 10 \
    -P analyze \
    -O drop
~~~
Since an UDP stream has no end, you need to specify some stop condition (here 10 seconds).

The command `tsanalyze` is just a legacy shortcut for:
~~~
tsp -I file ... -P analyze ... -O drop
~~~
which consequently works on files only.
