### ISSUE TITLE
virus in the last window windows binaries (3-19-1520.exe)

### ISSUE THREAD

**Issue by marcabramson** [tsduck/tsduck#499]
Hi Thierry
just installed the last window binaries, but my antivirus (bitdefender) has reported this
"  Le fichier C:\Program Files\TSDuck\bin\tsdektec.exe est infecté par Gen:Variant.Razy.583105 et a été placé en quarantaine"

can you check if there is a problem....
thanks

**Comment by lelegard** [comment]
Hi Marc,

If you use the official binaries from GitHub (or tsduck.io), I think that this is just a false positive from your antivirus. It happens.

The official binaries for Windows are built on a Win10 virtual machine running using VMware on may iMac. This VM is used to build TSDuck and run its test suite only.

For the 64-bit version, tsdektec.exe is 82944 bytes large and its SHA-1 is the following:
`257aa2a33d255a671f7386782afff7292c030cd9`

If you have the same thing, you can be confident that this is a false positive. Otherwise, check where you got the exe from.
