### ISSUE TITLE
merge and tsswitch

### ISSUE THREAD

**Issue by Worker35** [tsduck/tsduck#665]
is-it possible to use a tsswitch just behind a merge. In fact I want to use the result of the switch to merge it in a MPTS.
Thanks

**Comment by lelegard** [comment]
The `merge` plugin uses the output of the command it launches. So, to use the output of a `tsswitch` command as input of a `merge` plugin, the global command should look like this:
~~~
tsp ... -P merge "tsswitch -I ... -I ..." ...
~~~
Note the quote around the complete `tsswitch` command because the whole command is a parameter of the `merge` plugin.

Of course, if the `tsswitch` command is long, I would recommend to either write it in a shell script and run that shell script in the `merge` plugin or use the TSDuck partial command line redirection from a file (see the TSDuck user's guide, section 3.1.5).

**Comment by Worker35** [comment]
Perfect! it works very well. (a quote forgotten in a quite long command )
Thanks!
