### ISSUE TITLE
need plugins same as tsstuff and tsfixcc utility

### ISSUE THREAD

**Issue by samerajarmeh** [tsduck/tsduck#68]
i need to add final bitrate value to output because i am uses dveo dvbmasterfd cards that didnt support add nessesary nulls to meet final bitrate

**Comment by lelegard** [comment]
For an equivalent to `tsfixcc`, use `-P continuity --fix`.

For `tsstuff`, it is a bit more complicated. Within `tsp`, a plugin cannot add or create new packets. See the TSDuck user's guide [here](https://tsduck.io/download/docs/tsduck.pdf), the documentation of `tsp`, and especially the section named "Modifying, inserting and deleting packets", page 45.

If the only reason is that the DVEO card cannot add null packets, this should be addressed in another way. I do not know the DVEO products. Currently, TSDuck only supports Dektec ASI cards. So, to support new ASI cards, you need to develop your own output plugin based on the DVEO SDK. In that case, you should add the null packets in the output plugin, between output packets, when necessary. A plugin is made to hide the specificities of a device and since the lack of null packet insertion is a limitation of this device, it seems logical to address this in the output plugin. 

If you do not use a specific output plugin for DVEO, you probably pipe `tsp` output into a specific DVEO application. In that case, you can try to insert `tsstuff` in the pipe. I never tried this but it probably works.
