### ISSUE TITLE
spliceinject immediate with an INVALID_PTS value of @0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by EQMOD** [tsduck/tsduck#72]
Hi,
I noticed from the spliceinject plugin that when i manually inject via XML - UDP  using immediate mode, the PTS value used is @0xFFFFFFFFFFFFFFFF (tagged as INVALID_PTS from the code). I can verify this based on the verbose messages generated from the rmsplice plugin. Is it possible to automatically use actual PTS values from the current stream (probably from the current PTS value + offset plugin parameters) during an "immediate" spliceinject? Thanks.

**Comment by lelegard** [comment]
Hi,

Which PTS are we talking about here? In immediate mode, there is no PTS inside the command. In the definition of `splice_insert()` in the SCTE 35 standard, all `splice_time` are subject to the condition `splice_immediate_flag == 0`.

Internally, the plugin `spliceinject` uses a queue of events which are sorted by PTS time, using the invalid value FF..FF when the event has no time. This FF..FF value means "dequeue asap, don't wait for a specific time".

If this fake PTS value is displayed in verbose messages, this is no very nice, I agree. I will try to fix this.

Is there any malfunctioning otherwise ?

**Comment by EQMOD** [comment]
No issue actually. It is just im trying to trigger the rmsplice event via spliceinject udp and rmsplice needs a valid pts.

**Comment by EQMOD** [comment]
during a spliceinject, there is no way for me to determine the current pts value running on the stream. What if during an immediate=true splice insert, the pts value is added within the plugin based on the current pts value  running on the stream plus a time offset

**Comment by lelegard** [comment]
For splice injection, people want _their_ splice commands to be injected. So, I do not like the idea of modifying splice commands.
