### ISSUE TITLE
[Q] 

### ISSUE THREAD

**Issue by EnoSat** [tsduck/tsduck#890]
Hi,
analyze this stream https://mega.nz/file/YIEWmTKR#U293oku9jhmhfX-hnLkyq3smAV2Tq9G3v9Rmm4GL_D8
verbose output show problem with **TID 114 (0x72)** on PID 16 (0x0010),
![capture_008_03112021_190527](https://user-images.githubusercontent.com/4271667/140172128-fce51673-3191-46af-b178-fd4278477726.png)
next TID without attention on PID 18 (0x0012)
![capture_011_03112021_194038](https://user-images.githubusercontent.com/4271667/140172626-18081c0d-b559-43cd-9d7c-a09a84a5cef1.png)
Personally, I haven't encountered **Table_ID 0x72** yet, what is it actually used for?

**Comment by lelegard** [comment]
Hi @EnoSat 

This is the DVB-defined "Stuffing Table" (ST). See ETSI EN 300 468, section 5.2.8. This is rarely used, typically to overwrite an existing section in some retransmitter. These sections are just stuffing, they carry no particular semantics and shall be ignored.

The "unexpected TID" warning is issued by the TSDuck `psi` plugin because the only expected PSI/SI on PID 16 is a NIT. This is just a warning to draw your attention to this unexpected table.

Your TS must have gone through some retransmitter, transrater or transmux which, for some reason, decided to erase the input NIT and replace it with stuffing sections.

**Comment by lelegard** [comment]
As a side note, unlike a few applications, `tsp -vvv` won't be more verbose than `tsp -v`. More verbosity is activated though option `--debug` or `-d` with optional higher levels such as `-d2`, `--debug=10`, etc. The default debug level is 1, the lowest.

**Comment by EnoSat** [comment]
thanks
