### ISSUE TITLE
[BUG] Spliceinject unable to insert more than one SCTE-35 splice in offline TS file

### ISSUE THREAD

**Issue by moving-digital** [tsduck/tsduck#938]
Hi @lelegard 

#### Bug description:
I'm trying to inject multiple SCTE-35 cues in an offline TS file. For each cue, there is an associated XML file.
My test involves 3 SCTE-35 cues, therefore 3 XML files.
If I independently try to insert only SCTE-35 cue in the TS file one by one, it will be inserted.
However, if I try to insert the 3 of them, only the first one will be injected in the TS, and the other two will be discarded.
PS: All the cues should be inserted, as the first one (that is working) is located at the very beginning of the TS file, followed by the second splice in the middle, and the third one around the end. 

#### How to reproduce:
The TS input file has been provided by email, as well as here: https://we.tl/t-db6tlKPMJu

TSP command:
`tsp --add-input-stuffing 1/10 -I file test.ts -P pmt --service 1 --add-programinfo-id 0x43554549 --add-pid 111/0x86 -P spliceinject --service 1 --files 'scte35_vod_insert_*.xml' --wait-first-batch -P zap 1 -P filter --negate --pid 0x1FFF -O file test-output.ts`

Cue1 scte35_vod_insert_1.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tsduck>
	<splice_information_table protocol_version="0" pts_adjustment="0" tier="0x0FFF">
		<metadata PID="111"/>
		<splice_insert splice_event_id="1" splice_event_cancel="false" out_of_network="true" pts_time="234000" splice_immediate="false" unique_program_id="1" avail_num="0" avails_expected="0">
			<break_duration auto_return="true" duration="5490000"/>
		</splice_insert>
	</splice_information_table>
</tsduck>
```

Cue2 scte35_vod_insert_2.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tsduck>
	<splice_information_table protocol_version="0" pts_adjustment="0" tier="0x0FFF">
		<metadata PID="111"/>
		<splice_insert splice_event_id="2" splice_event_cancel="false" out_of_network="true" pts_time="32965200" splice_immediate="false" unique_program_id="2" avail_num="0" avails_expected="0">
			<break_duration auto_return="true" duration="10980000"/>
		</splice_insert>
	</splice_information_table>
</tsduck>
```

Cue3 scte35_vod_insert_3.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tsduck>
	<splice_information_table protocol_version="0" pts_adjustment="0" tier="0x0FFF">
		<metadata PID="111"/>
		<splice_insert splice_event_id="3" splice_event_cancel="false" out_of_network="true" pts_time="83476800" splice_immediate="false" unique_program_id="" avail_num="0" avails_expected="0">
			<break_duration auto_return="true" duration="16470000"/>
		</splice_insert>
	</splice_information_table>
</tsduck>
```

#### Expected behavior:
All the SCTE-35 cues should be available at the output.
Is it that the "--files" joker / wildcard in the command is not working as expected?
Or is it that spliceinject plugin just reads the first XML file and discards the rest?

#### Errors and logs:
No error on TSP.

#### Environment:
 - OS: Linux
 - OS version: CentOS 7.9 and Debian11
 - TSDuck full version: 3.30-2686 and 3.30-2696
 - Installation type: Official

**Comment by lelegard** [comment]
Your input is a TS file which is read at disk speed and the whole processing is done at that speed.

In parallel (I really mean in parallel, from an independent thread), splice commands are read from XML files. When loaded, XML files are converted into binary sections and queued for insertion. They are dequeued when it is time to inject.

On a real-time TS, there is no issue since the input arrives at playout speed. There is plenty of time to load XML files if they arrive in advance.

With input TS file, since the TS files and XML file processing occur in parallel at similar speeds, there is no guarantee that the XML files are loaded before the TS processing reaches the insertion point. In that case, the splice section is simply discarded because out of date.

The option `--wait-first-batch` is designed to avoid this. TS processing is delayed until the first batch of splice sections is loaded. This may not be very clear (and I may improve the documentation) but "first batch of sections" means "all sections in the first XML file". Since you have 3 XML files, `--wait-first-batch`  means start the TS processing after loading the first file. The second and third files are loaded in the XML processing thread immediately after. But TS processing already started in parallel. What happens is then undeterministic. The other 2 XML files can be loaded first or not. It depends on the system. You may have two different behaviours on two different systems.

The solution is to store the 3 splice commands in the same "first batch", meaning the same file:
~~~
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tsduck>
	<splice_information_table ...>
		...
	</splice_information_table>
	<splice_information_table ...>
		...
	</splice_information_table>
	<splice_information_table ...>
		...
	</splice_information_table>
</tsduck>
~~~

Splice insertion is targeted to real-time stream processing. The option `--wait-first-batch` is just a trick to be allowed to run non-regression tests on TS files in automated mode without timing undeterminism. You may use it for any other TS file processing usage but be sure to place all splice commands in one single XML file.

I currently do not have time to test your TS file but I suspect that the explanation above is correct.
